### ISSUE TITLE
debugger not breaking in VSCode

### ISSUE THREAD

**Issue by fabriciopapa** [godotengine/godot-vscode-plugin#168]
VSCode is connected to the GDScript language server but it is not breaking when running the game in Godot.

I'm running Godot Engine v.3.2.1.stable.official and VSCode 1.44.2 on Ubuntu 18.04.3.

I appreciate any help you can provide.

`[2020-05-02 17:58:37.884] [renderer5] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.relative (path.js:1054:5)
	at GodotDebugData.set_breakpoint (/.vscode/extensions/geequlim.godot-tools-1.1.0/out/debugger/debug_runtime.js:53:38)
	at /.vscode/extensions/geequlim.godot-tools-1.1.0/out/debugger/debug_session.js:211:37
	at Array.forEach (<anonymous>)
	at GodotDebugSession.setBreakPointsRequest (/.vscode/extensions/geequlim.godot-tools-1.1.0/out/debugger/debug_session.js:209:26)
	at GodotDebugSession.dispatchRequest (/.vscode/extensions/geequlim.godot-tools-1.1.0/node_modules/vscode-debugadapter/lib/debugSession.js:357:22)
	at GodotDebugSession.dispatchRequest (/.vscode/extensions/geequlim.godot-tools-1.1.0/node_modules/vscode-debugadapter/lib/loggingDebugSession.js:54:15)
	at GodotDebugSession.handleMessage (/.vscode/extensions/geequlim.godot-tools-1.1.0/node_modules/vscode-debugadapter/lib/protocol.js:60:18)`

**Comment by Razoric480** [comment]
Looks like the project path variable is in some sort of invalid state, which leads it to be undefined. Can you post your launch.json file?

**Comment by fabriciopapa** [comment]
Hey @Razoric480, changed permissions to the project folder and started to work. Closing it.

**Comment by erikreedstrom** [comment]
Hey, I'm getting this as well. Clean setup. Rarely I can get it to break, but most of the time I get the same error as above.

**Comment by Razoric480** [comment]
Can you check out #175 - I posted a comment with an altered VSIX file. I'd like to rule out that those two aren't the same bugs.
