### ISSUE TITLE
Error: Unable to resolve resource

### ISSUE THREAD

**Issue by TCROC** [godotengine/godot-vscode-plugin#260]
I keep getting this error when trying to go to a symbol in GD Script in VS Code

![image](https://user-images.githubusercontent.com/24307049/108373926-682e5280-71ce-11eb-973a-b259ac2da65c.png)

[2021-02-18 08:12:34.225] [renderer1] [error] Unable to resolve resource res://new_script.gd: Error: Unable to resolve resource res://new_script.gd
    at doCreateReferencedObject (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:59343)
    at doCreateReferencedObject (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:59306)
    at async h.createModelReference (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:60954)
    at async hr.resolve (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1753:81504)
    at async _o.setInput (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1876:3717)
    at async u.doSetInput (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1584:10520)
    at async u.openEditor (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1584:9082)
    at async file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2265:15707
    at async Ti.openEditor (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2265:14306)
    at async L.openEditor (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:78360)
    at async dn.openSymbol (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1283:14984)

Ubuntu 20.04
Using the Godot-Tools extension in VS Code
Godot Engine v3.2.3.stable.mono.official

**Comment by Calinou** [comment]
It looks like VS Code is trying to open `res://` as an URL. Is there any way to prevent this?

**Comment by Shatur95** [comment]
@TCROC, sorry for the off-topic, but how did you get a colored output?

**Comment by TCROC** [comment]
> @TCROC, sorry for the off-topic, but how did you get the colored output?

I just took a snip of the VS Code Log (Window) output.  Nothing special.

**Comment by Shatur95** [comment]
Oh, got it. Only default output logs have colored output.

**Comment by TCROC** [comment]
Ya.  I got the error notification in VS Code, so I checked the logs.  I expected it to be under "Godot", but it wasn't.  The verbose error message was actually under "Log (Window)"

**Comment by TCROC** [comment]
Just checking to to see if there are any updates on this issue?

**Comment by Razoric480** [comment]
This will be fixed by godotengine/godot#49687
