### ISSUE TITLE
launching does not appear to work

### ISSUE THREAD

**Issue by darkconsole** [godotengine/godot-vscode-plugin#365]
### Godot version

3.4

### VS Code version

1.67

### Godot Tools VS Code extension version

1.3.0

### System information

W10

### Issue description

```
[2022-05-18 12:58:18.321] [renderer3] [error] path.endsWith is not a function: TypeError: path.endsWith is not a function
    at is_powershell_path (c:\Users\dark\.vscode-insiders\extensions\geequlim.godot-tools-1.3.0\out\godot-tools.js:109:42)
    at escape_command (c:\Users\dark\.vscode-insiders\extensions\geequlim.godot-tools-1.3.0\out\godot-tools.js:137:81)
    at run_godot (c:\Users\dark\.vscode-insiders\extensions\geequlim.godot-tools-1.3.0\out\godot-tools.js:156:34)
    at c:\Users\dark\.vscode-insiders\extensions\geequlim.godot-tools-1.3.0\out\godot-tools.js:177:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

control pallete, godot run, select binary... nada.

**Comment by darkconsole** [comment]
not using powershell here i just short-circuited is_powershell_path and it works. so the problem is just in that little function.

**Comment by darkconsole** [comment]
still happens in 1.3.1

**Comment by DaelonSuzuka** [comment]
With the release of `2.0.0`, this issue is outdated. The "run project" command has been removed, if you want to run your project you should use the debugger or configure a task.
