### ISSUE TITLE
The debugger doesn't show any data

### ISSUE THREAD

**Issue by chsxf** [godotengine/godot-vscode-plugin#699]
### Godot version

4.3

### VS Code version

1.92.2

### Godot Tools VS Code extension version

2.1.0

### System information

macOS Sonoma 14.6.1

### Issue description

The debugger doesn't show any data (locals, members or globals) and watches are also not working. It is also impossible to update the list of watches while the debugger is running.

### Steps to reproduce

- Place a breakpoint in any GDScript
- Run your game until reaching the breakpoint
- The debugger panel in VSCode should be empty (except for the active scene and inspector)

**Comment by umutseven92** [comment]
Can confirm the same issue. Locals, members and globals are all empty. Same specs as the OP; Godot 4.3, Godot Tools 2.1.0, VSCode 1.92.2, Sonoma 14.6.1.

**Comment by DaelonSuzuka** [comment]
Share your `launch.json`.

**Comment by umutseven92** [comment]
I use the default `launch.json`.

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "GDScript Godot",
			"type": "godot",
			"request": "launch",
		}
	]
}
```

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-vscode-plugin/issues/432 (possible duplicate?).

**Comment by umutseven92** [comment]
@Calinou As far as I can see, that issue was caused by Headless LSP being on, which isn't the case here.

**Comment by chsxf** [comment]
In my case, the problem is present with or without Headless LSP

**Comment by periodyctom** [comment]
I'm experiencing the same issue with 4.3, not using any extra launch options:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "GDScript Godot",
            "type": "godot",
            "request": "launch",
            "project": "${workspaceFolder}",
            "address": "127.0.0.1",
            "port": 6007,
        }
    ]
}
```

I'm using VS Codium on x64 Linux if that helps narrow it down any.

**Comment by periodyctom** [comment]
Another thing I noted, it seems to hang on `match` statements, I can't step continue with `F10` after it hits the end of a match block.

**Comment by n4nn31355** [comment]
Godot version: 4.3
VS Code: 1.92.2
Godot Tools: 2.1.0

I have the same issue on one project, but it works on another.
The "launch.json" and vscode settings are the same for both projects.

I see an extension host errors when running project with issue.

Run without breakpoints. Value is always the same:
```
[error] RangeError: The value of "offset" is out of range. It must be >= 0 and <= 112. Received 116
	at boundsError (node:internal/buffer:88:9)
	at Buffer.readUInt32LE (node:internal/buffer:222:5)
	at Qc.decode_UInt32 (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:42169)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:38869)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.get_dataset (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41034)
	at Zc.on_data (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:51357)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

Run with breakpoint. Value depends on breakpoint.
First error happens on start, second only on breakpoint.
```
[error] RangeError: The value of "offset" is out of range. It must be >= 0 and <= 124. Received 128
	at boundsError (node:internal/buffer:88:9)
	at Buffer.readFloatForwards [as readFloatLE] (node:internal/buffer:534:5)
	at Qc.decode_Float32 (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41916)
	at Qc.decode_Vector3f (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:46401)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:39354)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.get_dataset (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41034)
	at Zc.on_data (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:51357)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
2024-09-04 00:43:25.237 [error] RangeError: The value of "offset" is out of range. It must be >= 0 and <= 172. Received 176
	at boundsError (node:internal/buffer:88:9)
	at Buffer.readUInt32LE (node:internal/buffer:222:5)
	at Qc.decode_UInt32 (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:42169)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:38869)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.decode_Array (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41384)
	at Qc.decode_variant (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:40363)
	at Qc.get_dataset (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:41034)
	at Zc.on_data (c:\Users\n4nn31355\.vscode\extensions\geequlim.godot-tools-2.1.0\out\extension.js:214:51357)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

Not sure how to debug it further at this point.

**Comment by umutseven92** [comment]
Just checked and I have the same error as @n4nn31355. This is when a breakpoint is hit:

```
2024-09-03 22:14:01.469 [error] RangeError: The value of "offset" is out of range. It must be >= 0 and <= 120. Received 124
	at boundsError (node:internal/buffer:88:9)
	at Buffer.readUInt32LE (node:internal/buffer:222:5)
	at Qc.decode_UInt32 (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:42169)
	at Qc.decode_variant (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:38869)
	at Qc.decode_Array (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:41384)
	at Qc.decode_variant (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:40363)
	at Qc.decode_Array (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:41384)
	at Qc.decode_variant (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:40363)
	at Qc.decode_Array (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:41384)
	at Qc.decode_variant (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:40363)
	at Qc.get_dataset (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:41034)
	at Zc.on_data (/Users/USERNAME/.vscode/extensions/geequlim.godot-tools-2.1.0/out/extension.js:214:51357)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by n4nn31355** [comment]
The problem seems to appear when using typed arrays with built-in types.
Possible solution in #708

**Comment by n4nn31355** [comment]
Code to reproduce:
```python
class_name MainLevel extends Node3D

func _ready() -> void:
    Performance.add_custom_monitor("custom/the/test", _get_calculation_performance)

func _unhandled_input(event: InputEvent) -> void:
    if event.is_action_pressed("ui_cancel"):
        _register_monitor()

func _register_monitor() -> void:
    Performance.add_custom_monitor("custom/the/test_more", _get_calculation_performance)

func _get_calculation_performance() -> float:
    return 0
```

**Comment by NathanNgo** [comment]
Having the same issue, and would love to get some traction on this issue, as I'd love to have the debugger working again on 4.3.

**Comment by DaelonSuzuka** [comment]
> Is there a particular maintainer we should ping

It's just me, and I've been too busy to look into these recently. There's multiple debugger related complaints open right and it's quite likely they're all related under the hood, but unfortunately that also means that it's possibly a multi-day day job to unravel what's going on. 

I might be able to look at it this weekend, but obviously I can't promise anything.

**Comment by NathanNgo** [comment]
Hi @DaelonSuzuka, I appreciate the response and I'm grateful for the time you spend maintaining this codebase!

While it would be awesome to have the debugger working again, please don't feel any pressure to do so if you don't have the time!

**Comment by DaelonSuzuka** [comment]
Good news, it doesn't die when decoding typed arrays now.

![image](https://github.com/user-attachments/assets/166d131f-5f21-40c7-b99d-a76db4ef4bd0)

It's gonna take... a lot of work to carry that information through to VSCode's debugger interface, but this should at least keep the debugger from blowing up. 

@Calinou I'm gonna get this fix plus a couple others cleaned up and merged, can you publish a hotfix later today maybe?

**Comment by DevAndrewGeorge** [comment]
Any chance on getting that hotfix deployed?

**Comment by DaelonSuzuka** [comment]
`v2.2.0` was published today and should be available in the marketplace now. Please make sure your extension updates and let me know if you're still experiencing this behavior.

**Comment by umutseven92** [comment]
@DaelonSuzuka The problem seems to still occur on `2.2.0`, with the same error:

```
2024-09-25 01:04:02.214 [error] RangeError: The value of "offset" is out of range. It must be >= 0 and <= 192. Received 196
	at boundsError (node:internal/buffer:88:9)
	at Buffer.readUInt32LE (node:internal/buffer:222:5)
	at Qc.decode_UInt32 (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:42447)
	at Qc.decode_variant (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:38878)
	at Qc.decode_Array (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:41515)
	at Qc.decode_variant (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:40403)
	at Qc.decode_Array (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:41515)
	at Qc.decode_variant (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:40403)
	at Qc.decode_Array (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:41515)
	at Qc.decode_variant (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:40403)
	at Qc.get_dataset (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:41165)
	at Zc.on_data (/Users/umutseven/.vscode/extensions/geequlim.godot-tools-2.2.0/out/extension.js:214:51883)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23
```

**Comment by DaelonSuzuka** [comment]
@umutseven92 I can't reproduce it on my end, can you share the variable declaration that's causing the failure?

**Comment by mihe** [comment]
I believe I tracked down the remaining issue with typed arrays. I put up a PR for it here: #731.

**Comment by gilad905** [comment]
I installed the extension now and I still notice this bug.
Windows
godot-tools v2.3.0
Godot v4.3.stable.official [77dcf97d8]
VS code settings:
    "godotTools.editorPath.godot4": "path\\to\\my\\Godot_v4.3-stable_win64.exe",
    "godotTools.lsp.serverHost": "127.0.0.1",
    "godotTools.lsp.serverPort": 6008,

launch.json:
![Image](https://github.com/user-attachments/assets/402fa0ad-7b6d-4227-8f92-261bb2a02d71)

Godot settings:
![Image](https://github.com/user-attachments/assets/ed6c4df9-8b98-41d7-9f52-66855e95ec4c)

VS code says "Connected to the GDScript language server at 127.0.0.1:6008

When I hit F5 I see the project opening up, I see output in the debug console, hitting a breakpoint does stop on the breakpoint but the "Run and Debug" variables panel is empty, hovering over a variable doesn't work, the REPL doesn't work.

**Comment by DaelonSuzuka** [comment]
@gilad905 Is there anything notable in the "Extension Host" Output channel? If there isn't, then you need to share your code or something, because this isn't enough information to help you.

**Comment by mihe** [comment]
> godot-tools v2.3.0

> When I hit F5 I see the game opening up, I see output in the debug console, hitting a breakpoint does stop on the breakpoint but the "Run and Debug" locals/members/globals/watch are empty, hovering over a variable doesn't work, the REPL doesn't work.

@gilad905 Keep in mind that there's been no new release since #731 was merged, so typed arrays containing script classes will still cause this to happen in the latest release on Visual Studio Marketplace, assuming that is in fact what's happening here.

**Comment by gilad905** [comment]
> > godot-tools v2.3.0
> 
> > When I hit F5 I see the game opening up, I see output in the debug console, hitting a breakpoint does stop on the breakpoint but the "Run and Debug" locals/members/globals/watch are empty, hovering over a variable doesn't work, the REPL doesn't work.
> 
> [@gilad905](https://github.com/gilad905) Keep in mind that there's been no new release since [#731](https://github.com/godotengine/godot-vscode-plugin/pull/731) was merged, so typed arrays containing script classes will still cause this to happen in the latest release on Visual Studio Marketplace, assuming that is in fact what's happening here.

Thank you, yes this is indeed the source of the problem! is there any workaround I can use in my code for now to replace the arrays?

**Comment by Etruscian** [comment]
I'm still having this issue, with the following error in Extension Host

`2024-12-22 15:17:34.034 [error] RangeError: The value of "offset" is out of range. It must be >= 0 and <= 112. Received 116
	at boundsError (node:internal/buffer:88:9)
	at Buffer.readUInt32LE (node:internal/buffer:222:5)
	at Zc.decode_UInt32 (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:42447)
	at Zc.decode_variant (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:38878)
	at Zc.decode_Array (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:41515)
	at Zc.decode_variant (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:40403)
	at Zc.decode_Array (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:41515)
	at Zc.decode_variant (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:40403)
	at Zc.decode_Array (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:41515)
	at Zc.decode_variant (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:40403)
	at Zc.get_dataset (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:41165)
	at Jc.on_data (c:\Users\sande\.vscode\extensions\geequlim.godot-tools-2.3.0\out\extension.js:214:51883)
	at Socket.emit (node:events:518:28)
	at Socket.emit (node:domain:489:12)
	at addChunk (node:internal/streams/readable:561:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
	at Readable.push (node:internal/streams/readable:392:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)`

What information would you need to reproduce locally?

**Comment by Kevin-Jonaitis** [comment]
@gilad905 you could build from the master branch to pull in @mihe's change...FWI I had to put in some extra work to do that but got it working, see my comment here: https://github.com/godotengine/godot-vscode-plugin/pull/749#issuecomment-2558782107

**Comment by umutseven92** [comment]
@DaelonSuzuka Can confirm that this is now fixed with 2.4.0. Thank you for the awesome work!

**Comment by DaelonSuzuka** [comment]
Thanks @umutseven92!

I'm considering this resolved.

**Comment by daniele-niero** [comment]
I'm still experiencing this problem in **Linux Ubuntu 25**, **Godot 4.6**

My configuration in VSCode
```
{
    "name": "Godot Pinned Scene",
    "type": "godot",
    "request": "launch",
    "project": "${workspaceFolder}/CosyCasette",
    "address": "127.0.0.1",
    "port": 6007,
    "scene": "pinned",
    "editor_path": "Godot_4.6",
    // engine command line flags
    "profiling": false,
    "single_threaded_scene": false,
    "debug_collisions": false,
    "debug_paths": false,
    "debug_navigation": false,
    "debug_avoidance": false,
    "debug_stringnames": false,
    "frame_delay": 0,
    "time_scale": 1.0,
    "disable_vsync": false,
    "fixed_fps": 60,
}
```

an example of code that I'm trying to debug:
```
func propagate_from(start: Vector3i):
    var queue: Array[Vector3i] = [start]

    while queue.size() > 0:
        var coord = queue.pop_front()
        var changed_neighbors = reduce_neighbors(coord)

        for n in changed_neighbors:
            queue.append(n)
```

Debugger correctly steps in, but no information about the various local variables

**Comment by Calinou** [comment]
Please continue the discussion in https://github.com/godotengine/godot-vscode-plugin/issues/987.
